### ISSUE TITLE
java.lang.NullPointerException while running soqlQuery action

### ISSUE THREAD

**Issue by thomasdziedzic** [neowit/tooling-force.com#17]
```
java.lang.NullPointerException
    at com.neowit.utils.JsonUtils$AnyJsonFormat$.write(JsonUtils.scala:18)
    at spray.json.PimpedAny.toJson(package.scala:39)
    at spray.json.CollectionFormats$$anon$3$$anonfun$write$3.apply(CollectionFormats.scala:52)
    at spray.json.CollectionFormats$$anon$3$$anonfun$write$3.apply(CollectionFormats.scala:50)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:50)
    at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:48)
    at spray.json.PimpedAny.toJson(package.scala:39)
    at com.neowit.utils.ResponseWriter$Message.toJSONObject(ResponseWriter.scala:44)
    at com.neowit.utils.ResponseWriter.println(ResponseWriter.scala:117)
    at com.neowit.apex.actions.SoqlQuery.act(SoqlQuery.scala:117)
    at com.neowit.apex.actions.Action$class.execute(Action.scala:89)
    at com.neowit.apex.actions.AsyncAction.execute(Action.scala:109)
    at com.neowit.apex.Executor.run(Runner.scala:131)
    at com.neowit.apex.Executor.execute(Runner.scala:49)
    at com.neowit.apex.Runner$.main(Runner.scala:33)
    at com.neowit.apex.Runner.main(Runner.scala)
```

Here is the soql query: `SELECT Id FROM Lock__c LIMIT 1 `

**Comment by neowit** [comment]
Hello @thomasdziedzic 

This is interesting. Did not expect SFDC to return null values.

What does the raw JSON output look like if you run the same query in [workbench](https://workbench.developerforce.com/login.php) -> "utilities" -> "REST Explorer" like so:  
GET: `/services/data/v37.0/query?q=SELECT+Id+FROM+Lock__c+limit+1`

**Comment by thomasdziedzic** [comment]
So continuous integration script that depends on the above started working again after I refreshed the sandbox. Unfortunately this means that I can't reliably reproduce this issue and so the output:

```
{
  "totalSize" : 0,
  "done" : true,
  "records" : [ ]
}
```

Probably doesn't show the problem anymore.
We can close or if you want.

**Comment by neowit** [comment]
> Unfortunately this means that I can't reliably reproduce this issue and so the output:

This is a unfortunate.
I have added a NULL value handling based on the stack trace you included, but this is not ideal, as this is just a guess rather than understanding the situation.

Thank you for reporting this.
Closing this for now.
