### ISSUE TITLE
grun not working

### ISSUE THREAD

**Issue by kalyanlanka** [neowit/tooling-force.com#8]
I'm trying to compile the project. `grun` is not working 

Here is the command I'm executing

````grun Apexcode soqlStatement *.sql````

I get the error

````
Exception in thread "main" java.lang.NoClassDefFoundError: ApexcodeLexer (wrong name: com/neowit/apex/parser/antlr/ApexcodeLexer)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.antlr.v4.runtime.misc.TestRig.process(TestRig.java:153)
	at org.antlr.v4.runtime.misc.TestRig.main(TestRig.java:143)

````

Same is the case with `grun Apexcode compilationUnit *.cls`

**Comment by neowit** [comment]
I have updated ["build"](https://github.com/neowit/tooling-force.com#building-tooling-forcecom) section in Readme. See if clarified build process will help you.
